### ISSUE TITLE
Using for generic list missing in DlTopicClasses.cs

### ISSUE THREAD

**Issue by jeffkenn2000** [dotnet/blazor-samples#25]
**Describe the issue**
I get a build error because the DITopicClasses.cs file is missing a reference to System.Collections.Generic. 

**To Reproduce**
1. Build solution

**Expected behavior**
The application should build without errors. 

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Additional context**
Add any other context about the issue here.

**.NET Version**
Output of `dotnet --info`.

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
I assume you're referring to either the 5.0/3.1 versions ... because I copied the file down from 6.0 without taking **_implicit namespaces_** into account 🙈😄. I'll fix this up.

Note tho that the snippet samples aren't really supposed to be buildable/runnable for the public. They're just here to make it easy to grab code. Their active purpose outside of that is just to supply snippets to the docs. More is explained on this point in this repo's README file.

Still tho ... I'll fix this up. Thanks for the issue!

**Comment by jeffkenn2000** [comment]
> I assume you're referring to either the 5.0/3.1 versions ... because I copied the file down from 6.0 without taking **_implicit namespaces_** into account 🙈😄. I'll fix this up.
> 
> Note tho that the snippet samples aren't really supposed to be buildable/runnable for the public. They're just here to make it easy to grab code. Their active purpose outside of that is just to supply snippets to the docs. More is explained on this point in this repo's README file.
> 
> Still tho ... I'll fix this up. Thanks for the issue!

Yes, Sorry about that, I should have mentioned that.

**Comment by guardrex** [comment]
No worries.

Just keep in mind what I was saying about these two being buildable/runnable. They're not really here for that purpose ... *YET* 😄. You aren't the first ask for them to be fully build/run capable with a nice link list on the Index for all of the scenarios. That could happen, but not this year. We're very 🏃😅 on the .NET 7 stuff right through the end of the year. It would be for sometime in 23H1 if it were to happen, and it can only happen then if there's time to do it.
