### ISSUE TITLE
Adjust docs for Entra for Customers (preview)

### ISSUE THREAD

**Issue by swegele** [dotnet/blazor-samples#251]
Firstly, thanks for this demo :-)  

I struggled for a long time to get this right...finally figured out the deltas and got it working with the applications authenticating against  MS Entra Id for Customers (preview).  

**BlazorWebAppOidc (server) value changes in Program.cs:**
`oidcOptions.Scope.Add("api://efc9xxxx-xxxx-xxxx-xxxx-xxxxxxxx2d15/Weather.Get");`
"`efc9xxxx-xxxx-xxxx-xxxx-xxxxxxxx2d15`" is the ClientId of the MinimalApiJwt App Registration

**MinimalApiJwt value changes in Program.cs:**
`jwtOptions.Audience = "api://efc9xxxx-xxxx-xxxx-xxxx-xxxxxxxx2d15";`
again "`efc9xxxx-xxxx-xxxx-xxxx-xxxxxxxx2d15`" is the ClientId of the WebAPI app registration
 
`jwtOptions.Authority = "https://sts.windows.net/87dcxxxx-xxxx-xxxx-xxxx-xxxxxxxx2c98/";`
`"87dcxxxx-xxxx-xxxx-xxxx-xxxxxxxx2c98"` is the TenantId of the Entra for customers directory

Notice the different value: **https://sts.windows.net/...** on the WebAPI side.
_That part cost me so much time.  Token kept getting rejected after I reviewed the docs repeatedly.  
I finally discovered the **iss:** value was different in the token than the authority._  
(someone that knew what they were doing probably would have identified it right away but dumb me didn't realize that iss: = authority)
Credit to [this article](https://auth0.com/docs/quickstart/backend/aspnet-core-webapi/03-troubleshooting) for helping me identify the problem

Thanks again, looking forward to .Net 9 and new templates.  Keep up the good work.

**Comment by guardrex** [comment]
Hello @swegele ... A couple of points ...

* Thanks for the feedback and kind words.
* It's always better to open issues for the docs from the bottom of the ***article***. This repo isn't the main working repo for issues. I'll take care of opening the issue and cross-linking it to this issue.
* I see that you're specifying `api://`-types of scopes because of your tenant domain. If the tenant domain is of the ME-ID type, the App ID URI goes with the `api://`. If the tenant is of the AAD B2C type, then the scope APP ID URI goes with the `https://contoso.onmicrosoft.com/4ba ... f9f5f0f/` format. I can see now that the article section didn't take this into account, just like the sample app here doesn't have a code comment on it ...

  https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=with-bff-pattern#configuration-1

  Therefore, I'll need to update it on both sides with more information calling out the type of tenant in use will dictate which App ID URI one can use.
* ... and the same is true for the Minimal API JWT project ...

  https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=with-bff-pattern#configuration-2

   ... which also doesn't call out the tenant type and only shows the AAD B2C format of the App ID URI.

Thanks for the report on this. I'll get it fixed tomorrow morning.

**Comment by guardrex** [comment]
I'll re-open and work from over here first.

... and this will be for tomorrow morning. I'm ***TOAST*** for the day 😩 and need to get off of this PC! 😆

**Comment by swegele** [comment]
Thank you sir!  Enjoy your day and "eat toast...don't be toast" :-)
