### ISSUE TITLE
Question about which template is preferrable or is the choice irrelevant?

### ISSUE THREAD

**Issue by Takhoffman** [dotnet/blazor-samples#290]
Greetings,

I am seeking some guidance.  If I wanted to build a WASM application and ultimately host the API in Azure API Management service.  For reference the OIDC provider would be Entra ID.   I assume I would still need an azure app service to serve the WASM site? Between these two templates, https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc and https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidcBff does it matter which one I go with or will they both work?  If BlazorWebAppOidc would work, is there something inherently "wrong" with not having a separate web api project when it's hosted in an Azure API Management service?

**Comment by guardrex** [comment]
Hello @Takhoffman ... Let me start by mentioning that your questions are on the borderline of what we can comment on here. We just work on the documentation for the base cases that the ASP.NET Core product unit have decided to cover. We don't get too deep into offering detailed hosting and deployment advice.

However .....

* A WASM application (standalone Blazor WebAssembly) and a Blazor Web App are two different kinds of apps. If you're asking about a standalone Blazor WebAssembly app, we have ...
  * [This article](https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-entra-id?view=aspnetcore-8.0) that focuses on Entra ID with MSAL (Microsoft Authentication Library) and a specific package for authenticating against Entra ID.
  * Alternatively, [this article](https://learn.microsoft.com/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-8.0&tabs=visual-studio) is based on general OIDC providers for Blazor WebAssembly, and you can actually use that with Entra ID if you want to, but we don't explain the exact Entra ID steps and configuration. You'd work that out on your own.
 * WRT "need an azure app service to serve the WASM site?" ... That's fine ***for Windows***. We guide devs away from Linux hosting with Azure App Service for Blazor WebAssembly apps. See [this section](https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#azure-app-service). What they really seem to favor for static sites tho is [Azure Static Web Apps](https://azure.microsoft.com/products/app-service/static). You aren't limited to Azure. Microsoft would be happy if you went with Azure ... it helps keep the lights on here! 😆 Seriously tho, you can use any static file server. You can even use a CDN (e.g., the Azure CDN).
 * You seem to switch in the first part of your remarks from a focus on Blazor WebAssembly to Blazor Web App, which is what the OIDC sample links you reference point to. I'll answer that question separately: You asked, "BlazorWebAppOidc would work, is there something inherently 'wrong' with not having a separate web api project." Research the "Backends for Frontends pattern" or "BFF pattern" to read all about it online. We link to [this content](https://learn.microsoft.com/azure/architecture/patterns/backends-for-frontends), but there's plenty out there on the Interwebs to explain it. MS's article links off to https://samnewman.io/patterns/architectural/bff/ for more information, and there are other resources out there. We have Blazor Web App OIDC security covered both ways. If you don't want to use BFF because it wouldn't benefit you, then use the non-BFF article pivot and sample app.

If you're asking about something else ... and given what I said earlier ... it's best if you contact the community to discuss your situation and seek advice. We can only remark on the scenarios that the ASP.NET Core Blazor product unit wants to discuss. We recommend the usual public support forums for chatting with folks about what you're doing and to get ideas and tips on what would be best for your specific situation ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://aspnetcore.slack.com/join/shared_invite/zt-1mv5487zb-EOZxJ1iqb0A0ajowEbxByQ#/shared-invite/email)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

I'll close this because there's no actionable work here as far as I can tell for documentation. It seems like you'll just need to research your hosting options further and decide what direction you'd like to take.
