### ISSUE TITLE
PersistentAuthenticationStateProvider vs RevalidatingAuthenticationStateProvider

### ISSUE THREAD

**Issue by jsmarsch** [dotnet/blazor-samples#296]
**Describe the issue**

This is a question, not an issue. Apologies if I'm asking in the wrong place.

I am working to port my .net 7 Server-Side Blazor app to .Net7 (it was using OIDC in .Net 7)it is using interactive components/signalR, but not WASM.  

I was curious as to why the template is using AuthenticationStateProvider + an offline scope and not RevalidatingAuthenticationStateProvider. Is this to make it work with WASM?  

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @jsmarsch ... The OIDC sample is for .NET 8 (Blazor Web App), so it's not going to be perfectly aligned in this exact form for a .NET 7 Blazor Server app. The article to accompany the sample is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

(... and I'm glad you said something here, because I found a broken link to reference source in the article that I need to fix.)

Anyway ... the answer I think is "no" to your question. We cover these providers at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-7.0&tabs=visual-studio#additional-security-abstractions

... and the idea AFAIK is just that the revalidating one does just that ... revalidates the auth state at regular intervals.

I'll closed as answered. Generally, it's best to open issues from the bottom of the article, as this repo is only for samples. I usually work on sample bug reports over here.

**Comment by jsmarsch** [comment]
Thank you!
