### ISSUE TITLE
Microsoft Graph

### ISSUE THREAD

**Issue by kasgithub8** [dotnet/blazor-samples#311]
Hi,
I know this is not an Issue but, how would I use Microsoft Graph inside of this application?

**Comment by guardrex** [comment]
Hello @kasgithub8 ... You didn't identify the application that you're referring to. If you're asking about one of the Blazor WASM samples, we have ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-8.0&pivots=graph-sdk-5

... if you're asking about one of the server-side samples (Blazor Server or Blazor Web App), we yield to the Microsoft Graph docs, such as ...

https://learn.microsoft.com/en-us/samples/microsoftgraph/msgraph-sample-aspnet-core/microsoft-graph-sample-aspnet-core-app/

... and the rest of their docs at ...

https://learn.microsoft.com/en-us/graph/

**Comment by kasgithub8** [comment]
Hi @guardrex,

Thanks for the quick answer. I'm using the template: [Blazor Web App with OIDC | ASP.NET 8.0 without BFF](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern).
What I tried so far is the clientSecretCredential stuff but it says, "/me request is only valid with delegated authentication flow".
And the 2nd link to the Blazor Server docs is out of date and the tutorial is gone.

**Comment by guardrex** [comment]
I'll open an issue to ask management if they want to add Graph to the sample+article. However, it might not be reached for a while. We're right in the middle of getting the .NET 9 docs up, and I'm working down a significant backlog of prior issues.

> "/me request is only valid with delegated authentication flow"

You'll need to read the MS Identity Platform docs and the Graph API docs. The access models (app versus delegated) are explained in their docs ... for example ... https://learn.microsoft.com/en-us/entra/identity-platform/permissions-consent-overview#delegated-access-access-on-behalf-of-a-user

I don't know what you mean by your last remark. That's an ASP.NET Core app that uses MS Identity Web, and the tutorial is there ...

https://github.com/microsoftgraph/msgraph-sample-aspnet-core/tree/main/

**Comment by guardrex** [comment]
I opened the issue at https://github.com/dotnet/AspNetCore.Docs/issues/33099.

As you work with the Graph docs to implement Graph, you'll want to adopt the weather data approach as the article and samples demonstrate. Namely, have the Auto component make a web API call to the server app, and the server app makes the call to Graph. I'm not 100% sure yet that that's what we'll do, but that's probably the approach that we'll be taking with these samples. An alternative is to use a custom service that on the server uses the Graph SDK and on the client uses an approach similar to what we do in the Blazor WASM+Graph article. We probably won't take that approach because it's more complicated.

For product support, we recommend the usual public support channels ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://aspnetcore.slack.com/join/shared_invite/zt-1mv5487zb-EOZxJ1iqb0A0ajowEbxByQ#/shared-invite/email)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
