### ISSUE TITLE
validateContext.Properties.GetTokenValue("refresh_token") is null

### ISSUE THREAD

**Issue by rrcnent** [dotnet/blazor-samples#331]
it seems that the validateContext.Properties.GetTokenValue("refresh_token") is null in this context, I used default out of the box configuruation with AzureB2C as the authority. I can login and authenticate but the system can not perform a refresh request , when it calls 
wait oidcOptions.Backchannel.PostAsync(tokenEndpoint,
            new FormUrlEncodedContent(new Dictionary<string, string?>()
            {
                ["grant_type"] = "refresh_token",
                ["client_id"] = oidcOptions.ClientId,
                ["client_secret"] = oidcOptions.ClientSecret,
                ["scope"] = string.Join(" ", oidcOptions.Scope),
                ["refresh_token"] = validateContext.Properties.GetTokenValue("refresh_token"),
            }));

The refresh token seems to always be null in this context

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment]
Hello @rrcnent ... Please open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Tell them in your issue that you're using the BWA+OIDC sample app at ...

https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc

... if that's the one that you're using (there's the BFF version of that sample, and your issue here doesn't say which one you're using) ...

Please add ...

```
cc: @guardrex https://github.com/dotnet/blazor-samples/issues/331
```

... to the bottom of your opening comment so that I can follow along. If a work issue for docs is needed, I'll open it from the bottom of the article. We don't usually work article issues from this repo, only patches and updates associated with article updates. We ask devs to open an issue using the link at the bottom of the article to get the issue opened in the right spot.
