### ISSUE TITLE
JavaScript interop

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/blazor-samples#41]
hey Luke, 
there is new [JavaScript interop available](https://github.com/dotnet/dotnet-api-docs/pull/8390) for .Net 7.

I created simple demo to show the new JavaScript interop in Blazor.
I'm not sure if you want to adopt it as is, but perhaps you could have look at it and extend one of the existing sample apps.

https://github.com/pavelsavara/blazor-wasm-hands-pose

There is also non-Blazor demo which has more complex interop logic
https://github.com/pavelsavara/dotnet-wasm-todo-mvc

(also please ping me on IM to discuss how to collaborate on further docs about the feature, thank you)

**Comment by pavelsavara** [comment]
cc @danroth27

**Comment by guardrex** [comment]
Thanks, @pavelsavara. Yes, I'll confer with @danroth27 to see what he wants to do.

> extend one of the existing sample app

We're trying to **avoid** putting up *new* sample apps because maintenance becomes a big time-sink and thus costly to the company💰💸. Extending the snippet samples with a companion section tho is cool. That controls our sample maintenance load. I'm going to close this in favor of an issue on the ASP.NET Core repo, and we'll triage the work from there.
